### ISSUE TITLE
Adding Several Views

### ISSUE THREAD

**Issue by lugwiri** [SW-Fantastic/Reader#8]
The reader and its entire structure is really amazing. I am really just starting learning programming but I have an Idea that is really burning inside. Since there is a reader, I am thinking about adding at least three views. One of the views will allow users to upload, edit and download the docs to read.  I will explain more about my ideas. What do you think?

**Comment by SW-Fantastic** [comment]
Interesting idea, but because I can't afford the overhead of the server, I don't currently plan to make network functions. In addition, this reader itself is involved in the convenience of personal management and utilization of various book resources, so it is a pity.
——————
有趣的想法，但是由于我无法负担服务器的开销，所以目前没有制作网络功能的打算，此外，这款阅读器本身是为了方便个人管理和利用各类书籍资源而涉及的，所以十分遗憾。
